name: CI-Nix

# Events that trigger workflow
on:
  # Runs on all pushes to branches
  push:
  # Runs on all PRs
  pull_request:
  # Manual Dispatch
  workflow_dispatch:

concurrency:
  # Behavior:
  # - Group all pull requests: latest push cancels previous ones
  # - Group all branches:
  #   - If main/version- branches: run serially
  #   - Else, latest push cancels previous ones
  group: >
    ${{
      (github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number)) ||
      (github.event_name == 'push' && format('branch-{0}', github.ref_name)) ||
      ''
    }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' || !(startsWith(github.ref_name, 'version-') || github.ref_name == 'main' || github.ref_name == 'dev') }}

jobs:
  prepare-pdks:
    name: Cache PDKs
    runs-on: ubuntu-24.04
    outputs:
      sky130_hash: ${{ steps.set-rev.outputs.sky130_hash }}
      gf180mcu_hash: ${{ steps.set-rev.outputs.gf180mcu_hash }}
      ihp-sg13g2_hash: ${{ steps.set-rev.outputs.ihp-sg13g2_hash }}
    steps:
      - uses: actions/checkout@v6
      - name: Python Dependencies
        run: |
          python3 -m pip install -r ./requirements.txt
      - name: Get Open PDKs Revision
        id: set-rev
        run: |
          echo "sky130_hash=$(python3 ./.github/scripts/get_pdk_hash.py ./cace/pdk_hashes.yaml --pdk-family sky130)" >> $GITHUB_OUTPUT
          echo "gf180mcu_hash=$(python3 ./.github/scripts/get_pdk_hash.py ./cace/pdk_hashes.yaml --pdk-family gf180mcu)" >> $GITHUB_OUTPUT
          echo "ihp-sg13g2_hash=$(python3 ./.github/scripts/get_pdk_hash.py ./cace/pdk_hashes.yaml --pdk-family ihp-sg13g2)" >> $GITHUB_OUTPUT
      - name: Cache sky130 PDK
        uses: actions/cache@v5
        with:
          path: ${{ github.workspace }}/.ciel-sky130
          key: cache-sky130-pdk-${{ steps.set-rev.outputs.sky130_hash }}
      - name: Enable sky130 PDK
        run: |
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          ciel enable --pdk-family sky130 --pdk-root ${{ github.workspace }}/.ciel-sky130 ${{ steps.set-rev.outputs.sky130_hash }}
      - name: Cache gf180mcu PDK
        uses: actions/cache@v5
        with:
          path: ${{ github.workspace }}/.ciel-gf180mcu
          key: cache-gf180mcu-pdk-${{ steps.set-rev.outputs.gf180mcu_hash }}
      - name: Enable gf180mcu PDK
        run: |
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          ciel enable --pdk-family gf180mcu --pdk-root ${{ github.workspace }}/.ciel-gf180mcu ${{ steps.set-rev.outputs.gf180mcu_hash }}
      - name: Cache ihp-sg13g2 PDK
        uses: actions/cache@v5
        with:
          path: ./.ciel-ihp-sg13g2
          key: cache-ihp-sg13g2-pdk-${{ steps.set-rev.outputs.ihp-sg13g2_hash }}
          enableCrossOsArchive: true
      - name: Enable ihp-sg13g2 PDK
        run: |
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          ciel enable --pdk ihp-sg13g2 --pdk-root ./.ciel-ihp-sg13g2 ${{ steps.set-rev.outputs.ihp-sg13g2_hash }}
      - name: Checkout submodules
        uses: actions/checkout@v6
        with:
          submodules: true
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
      - name: Set Up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: make dependencies
      - name: Lint
        run: |
          make lint
  build-py:
    runs-on: ubuntu-24.04
    needs: [lint, prepare-pdks]
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
      fail-fast: false
    name: Build and Unit Test (Python ${{ matrix.python-version }})
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
      - name: Set Up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache sky130 PDK
        id: cache-sky130-pdk
        uses: actions/cache@v5
        with:
          path: ${{ github.workspace }}/.ciel-sky130
          key: cache-sky130-pdk-${{ needs.prepare-pdks.outputs.sky130_hash }}
      - name: Enable sky130 PDK
        if: steps.cache-sky130-pdk.outputs.cache-hit != 'true'
        run: |
          pip3 install -r ./requirements.txt
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          ciel enable --pdk-family sky130 --pdk-root ${{ github.workspace }}/.ciel-sky130 ${{ needs.prepare-pdks.outputs.sky130_hash }}
      - name: Run Unit Tests
        run: echo TODO
  build-linux-x86_64:
    needs: lint
    runs-on: ubuntu-24.04
    name: Build (Nix/x86_64-linux)
    steps:
      - uses: actions/checkout@v6
      - name: Set up GITHUB_TOKEN
        run: |
          echo "GITHUB_TOKEN=${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - uses: ./.github/actions/setup_nix
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          nix_cache_domain: ${{ vars.NIX_CACHE }}
          nix_public_key: ${{ vars.NIX_PUBLIC_KEY }}
      - name: Build with Nix
        uses: ./.github/actions/build_nix
        with:
          nix_system: x86_64-linux
          run_tests: "true"
  build-linux-aarch64:
    needs: lint
    runs-on: ubuntu-24.04-arm
    name: Build (Nix/aarch64-linux)
    steps:
      - uses: actions/checkout@v6
      - name: Set up GITHUB_TOKEN
        run: |
          echo "GITHUB_TOKEN=${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - uses: ./.github/actions/setup_nix
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          nix_cache_domain: ${{ vars.NIX_CACHE }}
          nix_public_key: ${{ vars.NIX_PUBLIC_KEY }}
      - name: Build with Nix
        uses: ./.github/actions/build_nix
        with:
          nix_system: aarch64-linux
          run_tests: "true"
  build-darwin:
    strategy:
      matrix:
        os:
          [
            {
              name: "macOS 15 (Intel)",
              family: "darwin",
              runner: "macos-15",
              arch: "x86_64",
              nix: "x86_64-darwin",
            },
            {
              name: "macOS 15",
              family: "darwin",
              runner: "macos-15",
              arch: "aarch64",
              nix: "aarch64-darwin",
            },
          ]
      fail-fast: false
    needs: lint
    runs-on: ${{ matrix.os.runner }}
    name: Build (Nix/${{ matrix.os.nix }})
    steps:
      - uses: actions/checkout@v6
      - name: Set up GITHUB_TOKEN
        run: |
          echo "GITHUB_TOKEN=${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - uses: ./.github/actions/setup_nix
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          nix_cache_domain: ${{ vars.NIX_CACHE }}
          nix_public_key: ${{ vars.NIX_PUBLIC_KEY }}
      - name: Build with Nix
        uses: ./.github/actions/build_nix
        with:
          nix_system: ${{ matrix.os.nix }}
          shell: "zsh {0}"
          run_tests: "true"
  test:
    runs-on: ubuntu-24.04
    needs: [build-linux-x86_64, prepare-pdks]
    name: Test Design ${{ matrix.test_name }} (${{ matrix.pdk }})
    strategy:
      fail-fast: false
      matrix:
        test_name: ["test"]
        pdk: ["sky130A", "gf180mcuD", "ihp-sg13g2"]
        include:
          - pdk_family: sky130
            pdk: sky130A
          - pdk_family: gf180mcu
            pdk: gf180mcuD
          - pdk_family: ihp-sg13g2
            pdk: ihp-sg13g2
    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v5
        with:
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Check if Git
        run: |
          git status || true
          tree .git || true
      - name: Set up GITHUB_TOKEN
        run: |
          echo "GITHUB_TOKEN=${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - uses: ./.github/actions/setup_nix
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          nix_cache_domain: ${{ vars.NIX_CACHE }}
          nix_public_key: ${{ vars.NIX_PUBLIC_KEY }}
      - name: Build with Nix
        uses: ./.github/actions/build_nix
        with:
          nix_system: x86_64-linux
      - name: Check Nix
        run: |
          sudo du -hs /nix/store/* | sort -h | tail -n 10
          sudo tree /nix/store/*-openlane2 || true
      - name: Get PDK hash
        run: |
          echo "PDK_HASH=$(python3 ./.github/scripts/get_pdk_hash.py ./cace/pdk_hashes.yaml --pdk-family ${{ matrix.pdk_family }})" >> $GITHUB_ENV
      - name: Cache PDK
        id: cache-pdk
        uses: actions/cache@v5
        with:
          path: ./.ciel-${{ matrix.pdk_family }}
          key: cache-${{ matrix.pdk_family }}-pdk-${{ env.PDK_HASH }}
          enableCrossOsArchive: true
      - name: Enable PDKs
        if: steps.cache-pdk.outputs.cache-hit != 'true'
        run: |
          pip3 install -r ./requirements.txt
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          ciel enable --pdk-family ${{ matrix.pdk_family }} \
            --pdk-root ./.ciel-${{ matrix.pdk_family }} \
            ${{ env.PDK_HASH }}
      - name: Compile Verilog-A (ihp-sg13g2)
        if: matrix.pdk_family == 'ihp-sg13g2'
        run: |
          wget https://fides.fe.uni-lj.si/openvaf/download/openvaf-reloaded-20260616-linux_x64.tar.gz
          sudo tar -xvzf openvaf-reloaded-20260616-linux_x64.tar.gz -C /usr/bin/
          cd ./.ciel-${{ matrix.pdk_family }}/${{ matrix.pdk }}/libs.tech/verilog-a; source openvaf-compile-va.sh
      - name: Run Example (sky130)
        if: matrix.pdk_family == 'sky130'
        run: |
          PDK_ROOT=$(realpath ./.ciel-${{ matrix.pdk_family }}) PDK=${{ matrix.pdk }} nix develop --command bash -c "cd examples/sky130_cace_ip__ota5t/; cace"
      - name: Run Example (ihp-sg13g2)
        if: matrix.pdk_family == 'ihp-sg13g2'
        run: |
          PDK_ROOT=$(realpath ./.ciel-${{ matrix.pdk_family }}) PDK=${{ matrix.pdk }} nix develop --command bash -c "cd examples/sg13g2_cace_ip__ota5t/; cace"
      # Upload artifacts
      - name: Upload Artifacts
        if: matrix.pdk_family == 'sky130'
        uses: actions/upload-artifact@v4
        with:
          name: runs_sky130
          path: |
            examples/sky130_cace_ip__ota5t/runs/
      # Add summary
      - name: Add Markdown to Step Summary
        if: matrix.pdk_family == 'sky130'
        run: cat examples/sky130_cace_ip__ota5t/runs/*/summary.md >> $GITHUB_STEP_SUMMARY
      # Upload artifacts
      - name: Upload Artifacts
        if: matrix.pdk_family == 'ihp-sg13g2'
        uses: actions/upload-artifact@v4
        with:
          name: runs_ihp-sg13g2
          path: |
            examples/sg13g2_cace_ip__ota5t/runs/
      # Add summary
      - name: Add Markdown to Step Summary
        if: matrix.pdk_family == 'ihp-sg13g2'
        run: cat examples/sg13g2_cace_ip__ota5t/runs/*/summary.md >> $GITHUB_STEP_SUMMARY
